const form=document.getElementById('checkin-form');
const fields=['cycle','temperature','pain','nausea','energy','appetite','bowel','mouth','neuropathy','hearing','cognition','medicines','notes'];
const status=document.getElementById('save-status');
const reportStatus=document.getElementById('report-status');
const preview=document.getElementById('report-preview');
const historyKey='chemo-companion-history';
const contactKey='chemo-companion-contacts';
const contactFields=['care-hospital','care-team','urgent-phone','afterhours-phone','care-regimen'];
const contactStatus=document.getElementById('contact-status');
const urgentContactDisplay=document.getElementById('urgent-contact-display');
function getHistory(){try{return JSON.parse(localStorage.getItem(historyKey)||'[]')}catch(e){return []}}
function saveHistory(items){localStorage.setItem(historyKey,JSON.stringify(items))}
function getContacts(){try{return JSON.parse(localStorage.getItem(contactKey)||'{}')}catch(e){return {}}}
function saveContacts(data){localStorage.setItem(contactKey,JSON.stringify(data))}
function loadCurrent(){try{const saved=JSON.parse(localStorage.getItem('chemo-companion-checkin')||'{}');fields.forEach(id=>{if(saved[id]!==undefined)document.getElementById(id).value=saved[id]})}catch(e){}}
function formatDate(value){try{return new Date(value).toLocaleString()}catch(e){return value||''}}
function escapeHtml(value){return String(value).replace(/[&<>\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[ch]))}
function cleanPhone(value){return String(value||'').replace(/[^+0-9]/g,'')}
function v(item,key){return escapeHtml(item[key]||'—')}
function row(item){return `<tr><td>${formatDate(item.savedAt)}</td><td>${v(item,'cycle')}</td><td>${v(item,'temperature')}</td><td>${v(item,'pain')}</td><td>${v(item,'nausea')}</td><td>${v(item,'energy')}</td><td>${v(item,'appetite')}</td><td>${v(item,'bowel')}</td><td>${v(item,'mouth')}</td><td>${v(item,'neuropathy')}</td><td>${v(item,'hearing')}</td><td>${v(item,'cognition')}</td><td>${v(item,'medicines')}</td><td>${v(item,'notes')}</td></tr>`}
const headings='<tr><th>Date</th><th>Cycle / day</th><th>Temp °C</th><th>Pain /10</th><th>Nausea /10</th><th>Energy /10</th><th>Appetite /10</th><th>Bowel</th><th>Mouth / throat</th><th>Tingling / numbness</th><th>Hearing / ringing</th><th>Thinking / memory</th><th>Medicines taken</th><th>Patient notes</th></tr>';
function contactSummary(){const c=getContacts();const parts=[];if(c['care-hospital'])parts.push(`<strong>${escapeHtml(c['care-hospital'])}</strong>`);if(c['care-team'])parts.push(escapeHtml(c['care-team']));if(c['urgent-phone'])parts.push(`Urgent: <a href="tel:${cleanPhone(c['urgent-phone'])}">${escapeHtml(c['urgent-phone'])}</a>`);if(c['afterhours-phone'])parts.push(`After hours: <a href="tel:${cleanPhone(c['afterhours-phone'])}">${escapeHtml(c['afterhours-phone'])}</a>`);return parts.join(' · ')}
function regimenSummary(){const c=getContacts();return c['care-regimen']?escapeHtml(c['care-regimen']):''}
function renderContacts(){const c=getContacts();contactFields.forEach(id=>{const el=document.getElementById(id);if(el)el.value=c[id]||''});const summary=contactSummary();urgentContactDisplay.innerHTML=summary?`<strong>☎️ My cancer-team contact:</strong> ${summary}<br><span class="small">These details were entered on this device. Use the instructions given by your treating service.</span>`:'<strong>☎️ Cancer-team contact:</strong> Add your own oncology urgent-contact details below so they are easy to find when you need them.'}
function renderPreview(){const items=getHistory().slice().reverse();if(!items.length){preview.innerHTML='<p>No saved check-ins yet.</p>';return}const summary=contactSummary();const regimen=regimenSummary();preview.innerHTML=`${summary?`<p><strong>Care contact:</strong> ${summary}</p>`:''}${regimen?`<p><strong>Patient-entered chemotherapy medicines / regimen (verify against clinical record):</strong> ${regimen}</p>`:''}<div class="report-table-wrap"><table><thead>${headings}</thead><tbody>${items.map(row).join('')}</tbody></table></div><p class="small">This patient-entered summary is for discussion with the treating team. It is not a diagnosis or clinical interpretation.</p>`}
form.addEventListener('submit',e=>{e.preventDefault();const data={};fields.forEach(id=>data[id]=document.getElementById(id).value);data.savedAt=new Date().toISOString();localStorage.setItem('chemo-companion-checkin',JSON.stringify(data));const history=getHistory();history.push(data);saveHistory(history);status.textContent='✅ Saved on this device and added to your report history.';if(Number(data.temperature)>=38){status.textContent+=' 🌡️ A temperature of 38°C or higher can be a sign of infection during cancer treatment. Follow your cancer team’s urgent-contact instructions.'}renderPreview()});
document.getElementById('contact-form').addEventListener('submit',e=>{e.preventDefault();const data={};contactFields.forEach(id=>data[id]=document.getElementById(id).value.trim());saveContacts(data);contactStatus.textContent='✅ Care details saved on this device. Treatment details remain patient-entered and should be checked against the clinical record.';renderContacts();renderPreview()});
document.getElementById('clear-contacts').addEventListener('click',()=>{localStorage.removeItem(contactKey);contactFields.forEach(id=>document.getElementById(id).value='');contactStatus.textContent='Saved care details cleared from this device.';renderContacts();renderPreview()});
document.getElementById('clear-checkin').addEventListener('click',()=>{localStorage.removeItem('chemo-companion-checkin');form.reset();status.textContent='Current form cleared. Saved report history was not deleted.'});
document.getElementById('clear-history').addEventListener('click',()=>{localStorage.removeItem(historyKey);reportStatus.textContent='Saved report history cleared from this device.';renderPreview()});
document.getElementById('download-csv').addEventListener('click',()=>{const items=getHistory();if(!items.length){reportStatus.textContent='No saved check-ins to download yet.';return}const header=['date','cycle_day','temperature_c','pain_0_10','nausea_0_10','energy_0_10','appetite_0_10','bowel_changes','mouth_throat','tingling_numbness','hearing_ringing','thinking_memory','medicines_taken','notes'];const quote=x=>`"${String(x??'').replace(/"/g,'""')}"`;const keys=['savedAt','cycle','temperature','pain','nausea','energy','appetite','bowel','mouth','neuropathy','hearing','cognition','medicines','notes'];const lines=[header.join(','),...items.map(i=>keys.map(k=>quote(i[k])).join(','))];const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`osteosarcoma-chemo-checkins-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);reportStatus.textContent='⬇️ CSV downloaded to this device.'});
document.getElementById('print-report').addEventListener('click',()=>{const items=getHistory().slice().reverse();if(!items.length){reportStatus.textContent='No saved check-ins to report yet.';return}const report=window.open('','_blank');if(!report){reportStatus.textContent='Your browser blocked the report window. Allow pop-ups for this page and try again.';return}report.opener=null;const summary=contactSummary();const regimen=regimenSummary();report.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Osteosarcoma chemotherapy check-in report</title><style>body{font-family:system-ui,sans-serif;max-width:1600px;margin:2rem auto;padding:0 1rem;color:#111}h1{font-size:2rem}table{width:100%;border-collapse:collapse;margin:1.5rem 0;font-size:.78rem}th,td{border:1px solid #bbb;padding:.4rem;text-align:left;vertical-align:top}th{background:#f2f2f2}.note{padding:1rem;background:#f6f6f6;border-left:4px solid #555}@media print{button{display:none}body{margin:0;max-width:none}table{font-size:7.5pt}}</style></head><body><h1>Osteosarcoma chemotherapy check-in report</h1><p>Generated: ${new Date().toLocaleString()}</p>${summary?`<p><strong>Patient-entered care contact:</strong> ${summary}</p>`:''}${regimen?`<p><strong>Patient-entered chemotherapy medicines / regimen:</strong> ${regimen}</p>`:''}<p class="note"><strong>For treating team:</strong> This report contains patient-entered observations, contact details, chemotherapy regimen details and medicines. It does not confirm medication administration, regimen accuracy, contact accuracy, diagnosis, clinical interpretation or treatment recommendations. Please reconcile medicines and treatment details against the clinical record.</p><table><thead>${headings}</thead><tbody>${items.map(row).join('')}</tbody></table><p>Source: locally stored entries from the Osteosarcoma Chemo Companion. No server transmission is required to generate this report.</p><button onclick="window.print()">Print / Save as PDF</button></body></html>`);report.document.close();report.focus();reportStatus.textContent='📄 Report opened. Use Print and choose Save as PDF if you want a PDF copy.'});
loadCurrent();renderContacts();renderPreview();
